# Generated by Django 2.2.2 on 2019-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_library_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='bookid',
            field=models.CharField(blank=True, max_length=30, verbose_name='book id'),
        ),
    ]
