# Generated by Django 2.2.2 on 2019-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190702_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(null=True, to='home.Book'),
        ),
    ]
